# -*- coding: utf-8 -*-
"""AssignmentAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lCYRj9ZEUgyWeZs9uMOaHsBazthLnSAF
"""

#input the number of terms
n = int(input("Enter the no. of terms: "))

#first two terms
a, b = 0, 1

#print fibonacci sequence
print("Fibonacci sequence: ")
for _ in range(n):
  print(a,end=" ")
  a, b = b, a + b