# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWtQlW2v_HEW2q86g8qih4rcOrznQTW-
"""

#displaying "Hello World!" on the screen
#print is a Python defined default function, we are simply using it here
print("Hello World!")