# -*- coding: utf-8 -*-
"""assignmentai4.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18aPhtcpBkfhSAJQX2xcIkhG65IKSPBNL
"""

E = {0, 2, 4, 6, 8}  # Even numbers
N = {1, 2, 3, 4, 5}  # Some natural numbers

# Perform set operations
print("Union of E and N is", E | N)  # Union
print("Intersection of E and N is", E & N)  # Intersection
print("Difference of E and N is", E - N)  # Difference
print("Symmetric difference of E and N is", E ^ N)